# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(max_length=8, verbose_name='Matrícula'),
        ),
    ]
