# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pagseguro', 'PagSeguro'), ('deposito', 'Deposito'), ('paypal', 'Paypal')], default='deposito', max_length=20, verbose_name='Opção pagamento'),
        ),
    ]
