# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180220_1549'),
        ('checkout', '0007_remove_cartitem_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unity',
            field=models.ManyToManyField(to='catalog.Unidades'),
        ),
    ]
