# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_orderitem_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sub',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Código Comprasnet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
