# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20180319_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Código Comprasnet'),
            preserve_default=False,
        ),
    ]
