# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_orderitem_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
