# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_orderitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.PositiveIntegerField(default=1, verbose_name='Item'),
        ),
    ]
