# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_orderitem_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seq',
        ),
    ]
