# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_remove_orderitem_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
