# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['name_search'], 'verbose_name': 'Nome'},
        ),
        migrations.RemoveField(
            model_name='search',
            name='name',
        ),
        migrations.AddField(
            model_name='search',
            name='name_search',
            field=models.CharField(default='', max_length=100, verbose_name=''),
            preserve_default=False,
        ),
    ]
