# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_search_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='seq',
        ),
        migrations.AddField(
            model_name='search',
            name='slug',
            field=models.CharField(default='1', max_length=1, verbose_name=''),
        ),
    ]
