# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='unid',
            field=models.CharField(max_length=10, null=True, verbose_name='unidade'),
        ),
    ]
