# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Unidades', verbose_name='Unidades'),
        ),
    ]
