# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180220_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
