# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_unidades_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.CharField(default='', max_length=100, verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
