# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_unid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Código Comprasnet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pregao',
            field=models.CharField(default='', help_text='Preencher no formato nnn/aaaa', max_length=8, verbose_name='Pregão da última aquisição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='slug',
            field=models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
